# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Computes a weighted Pearson distance measure matrix. If ranks are used
#' this measure turns into weighted Spearman distance measure matrix.
#'
#'@param x input with columns containing each observation
#'@param w weights for all values in a obervation
#'@param useRanks indicates if Pearson should be computed on weighted ranks.
#'@param n_cores number of cores to use for parallel computation.
#'@return weighted Pearson distance measure matrix. If ranks are used
#' this measure turns into weighted Spearman distance measure matrix.
wCorDist <- function(x, w, useRanks, n_cores) {
    .Call('_ccImpute_wCorDist', PACKAGE = 'ccImpute', x, w, useRanks, n_cores)
}

